# Generated by Django 4.2.7 on 2023-11-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='AnomUser', max_length=22)),
                ('age', models.IntegerField(default=18, max_length=3)),
                ('status', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('email', models.CharField(max_length=50)),
                ('pfp', models.ImageField(blank=True, null=True, upload_to='profilepictures')),
            ],
        ),
    ]
